### ISSUE TITLE
Read Me doesn't cover the beer's description variable name.

### ISSUE THREAD

**Issue by benlachman** [AthensWorks/OBWapp-API#18]
At one point we defined it as `beer_description` and another as `description`. We should probably document which it is.

**Comment by rickychilcott** [comment]
Hmm... where is this @benlachman? https://github.com/AthensWorks/OBWapp-API/blob/master/README.md

**Comment by rickychilcott** [comment]
Fixed in fd3dfc31481719f7a835919d39d9b2f5b75dd595
