### ISSUE TITLE
Fix bug in /beers

### ISSUE THREAD

**Issue by rickychilcott** [AthensWorks/OBWapp-API#2]
https://github.com/AthensWorks/OBWapp-API#get-beers

Implement something like what @Bargs did [563aeeba2608e439a75122ba8c0191f35d9258e5].  @buswellj can you try this out locally or in prod?

**Comment by pagan8** [comment]
var sql = 'select *,(select count(*) from likes where beer_id = beers.id and likes.like_type = 1) as "taste_count",(select count(*) from likes where beer_id = beers.id and likes.like_type = 2) as "favorite_count" from beers;';

**Comment by pagan8** [comment]
this seems to do the trick and parses the count column names into something express.js will autoparse into the correct JSON...
