### ISSUE TITLE
Admin Interface

### ISSUE THREAD

**Issue by rickychilcott** [AthensWorks/OBWapp-API#5]
We need a simple admin interface for Weston or his designee to use.  Something like Express Admin ( [Docs](https://simov.github.io/express-admin/) | [NPM](https://www.npmjs.com/package/express-admin) )
could work. @buswellj suggested we could just write authenticated endpoints for each of these and build a web-interface.

At minimum we need HTTP Basic authentication, but multiple users with a proper authentication form would be ideal.

If we have to prioritize, the critical use cases are:

- [x] Add a new beer
- [x] Set [status](https://github.com/AthensWorks/OBWapp-API#establishments) (i.e. 'tapped', 'untapped', 'empty'...) for a given beer/establishment relationship
- [x] Add/edit establishment
- [x] Associate a beer with an establishment
- [x] Lookup geo-location based on address
- [x] List associated status while viewing a given beer
- [x] Add map with establishment location

In the future it could:
- [ ] Report how many tastes and favorites per beer
- [ ] Report ages of users who interact with the system

**Comment by pagan8** [comment]
There is now a very basic API for /admin, see the README file for details.

I will try to add auth to this shortly. But someone else will need to write the HTML / wrapper around the API calls...

**Comment by rickychilcott** [comment]
By way of a whole different rails project, we now have an admin interface. See https://github.com/AthensWorks/OBWapp-Admin-UI
